sudo: required
language: node_js
services:
  - docker

node_js:
  - "node"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: make docker-build
  
