# This file describes the menu layout
---
- Communicate:
  title: Communicate
  links:
      - News:
        title: News
        link: news
      - Events:
        title: Events
        link: events
      - Support:
        title: Support
        link: support
      - Biostar:
        title: Biostar
        link: https://biostar.usegalaxy.org
- Using Galaxy:
  title: Using Galaxy
  link: using-galaxy
  links:
      - Servers:
        title: Servers
        link: public-galaxy-servers
      - Learn:
        title: Learn
        link: learn
      - Main:
        title: Main
        link: main
      - Choices:
        title: Choices
        link: big-picture/choices
      - Tutorials:
        title: Support
        link: support
- Galaxy Project:
  title: Galaxy Project
  links:
      - About:
        title: About
        link: galaxy-project
- Deploy:
  title: Deploy Galaxy
  links:
      - Get Galaxy:
        title: Get Galaxy
        link: admin/get-galaxy
      - Cloud:
        title: Cloud
        link: cloud
      - Administration:
        title: Admin
        link: admin
      - Tool Config:
        title: Tool Config
        link: admin/tools/tool-config-syntax
      - Tool Shed:
        title: Tool Shed
        link: tool-shed
- Contribute:
  title: Contribute
  links:
      - Develop:
        title: Develop
        link: develop
      - Tools:
        title: Tools
        link: tools
      - Issues & Requests:
        title: Issues & Requests
        link: issues
      - Logs:
        title: Logs
        link: community/logs
      - Deployments:
        title: Deployments
        link: community/deployments
      - Teach:
        title: Teach
        link: teach
