# This file describes the menu layout
---
- Use:
  title: Use
  links:
      - Main:
        title: Main public site
        link: main
      - Servers:
        title: Public servers worldwide
        link: public-galaxy-servers
      - Cloud:
        title: Galaxy on the Cloud
        link: cloud
- Learn:
  title: Learn
  links:
      - Learn:
        title: Tutorials
        link: learn
      - Videos:
        title: Videos
        link: https://vimeo.com/groups/teachinggalaxy
- Teach:
  title: Teach
  links:
      - GTN:
        title: Galaxy Training Network
        link: teach/gtn
      - Trainers:
        title: Trainer Directory
        link: teach/trainers
      - Platform:
        title: Compute Platform Advice
        link: teach/computing-platforms
      - BP:
        title: Best Practices
        link: teach/best-practices
- Support:
  title: Support
  links:
      - BioStar:
        title: Galaxy BioStar Forum
        link: https://biostar.usegalaxy.org
      - Mailing Lists:
        title: Galaxy Mailing Lists
        link: mailing-lists
      - IM:
        title: Instant Messaging
        link: https://gitter.im/galaxyproject/Lobby
- Community:
  title: Community
  links:
      - Community:
        title: Community
        link: community
      - gcc2017:
        title: GCC 2017
        link: https://gcc2017.sciencesconf.org
- Deploy:
  title: Deploy & Develop
  links:
      - Install:
        title: Get Galaxy
        link: admin/get-galaxy
      - Administer:
        title: Administration
        link: admin
      - docs:
        title: Documentation
        link: docs
      - Tools:
        title: Tools
        link: tools
      - Codebase:
        title: Development
        link: develop
- Pulse:
  title: Pulse
  links:
      - News:
        title: Galactic News
        link: news
      - Events:
        title: Galactic Events
        link: events
      - Publications:
        title: Galactic Publications
        link: cite-u-like
      - Project Stats:
        title: Stats
        link: galaxy-project/statistics
