# This file describes the menu layout
---
- Use:
  title: Use
  links:
      - Main:
        title: Main Galaxy
        link: main
      - Servers:
        title: Public Servers
        link: public-galaxy-servers
      - Cloud:
        title: Cloud
        link: cloud
- Education:
  title: Education
  links:
      - Learn:
        title: Learn Galaxy
        link: learn
      - Teach:
        title: Teach
        link: teach
      - GTN:
        title: Training Network
        link: teach/gtn
- Community:
  title: Community
  links:
      - Community:
        title: About
        link: community
      - News:
        title: News
        link: news
      - Events:
        title: Events
        link: events
      - Publications:
        title: Publications
        link: cite-u-like
      - Project Stats:
        title: Stats
        link: galaxy-project/statistics
- Deploy:
  title: Deploy & Develop
  links:
      - Install:
        title: Get Galaxy
        link: admin/get-galaxy
      - Administer:
        title: Administration
        link: admin
      - docs:
        title: Documentation
        link: docs
      - Tools:
        title: Tools
        link: tools
      - Codebase:
        title: Development
        link: develop
      - api:
        title: API
        link: develop/api
- Support:
  title: Support
  links:
      - Support:
        title: Hub
        link: support
      - Biostar:
        title: Galaxy Biostar
        link: support/biostar
