# This file describes the menu layout
---
- Use: 
  title: Use
  links:
      - Main:
        title: Main public site
        link: main
      - Servers:
        title: Public servers worldwide
        link: public-galaxy-servers
      - Cloud: 
        title: Galaxy on the Cloud
        link: cloud
- Learn:
  title: Learn
  links:
      - Tutorials:
        title: Tutorials
        link: teach
      - Videos:
        title: Videos
        link: https://vimeo.com/groups/teachinggalaxy
      - Tours:
        title: Interactive Tours
        link: https://usegalaxy.org/tours/core.history
- Deploy:
  title: Deploy & Run
  links:
      - Install:
        title: Get Galaxy
        link: admin/get-galaxy
      - Administer:
        title: Administer Galaxy
        link: admin
      - RTFD:
        title: Read the Docs
        link: https://galaxy.readthedocs.io/en/master/index.html
      - Build Tools:
        title: Planemo
        link: https://github.com/galaxyproject/planemo
- Support:
  title: Support
  links:
      - BioStar:
        title: Galaxy BioStar Forum
        link: https://biostar.usegalaxy.org
      - Mailing Lists:
        title: Galaxy Mailing Lists
        link: mailing-lists
      - IM:
        title: Instant Messaging
        link: https://gitter.im/galaxyproject/Lobby
- Community:
  title: Community
  link: community
- Pulse:
  title: Pulse
  links:
      - News: 
        title: Galactic News
        link: news
      - Evens:
        title: Galactic Events
        link: events
      - Publications: 
        title: Galactic Publications
        link: cite-u-like
      - Project Stats:
        title: Stats
        link: galaxy-project/statistcs
