name: Add Gitpod Link

on:
  pull_request:
    types: [opened]

jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
    - name: Comment PR
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const pr = context.payload.pull_request
          github.issues.createComment({
            issue_number: pr.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `[Open in Gitpod](https://gitpod.io/#${pr.html_url})`
          })
